language: node_js
jobs:
  include:
    - stage: test
      if: type = pull_request AND branch = develop
      node_js: 6
      script:  
        - |
          npm run lint
    - stage: deploy
      if: type = push AND branch = develop
      node_js: 6
      script:  
        - |
          chmod +x deploy.sh
          ./deploy.sh